FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .
 
ARG AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID

ARG AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY 
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

ARG AWS_DEFAULT_REGION=AWS_DEFAULT_REGION 
ENV AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION

RUN python3 utils/mock_process.py

CMD ["python3", "src/main.py"]